# **Swiss Olympic Athlete Selection**

# **Abstract**

## **Problem:** 
Swiss Olympic selection criteria are PDF-based and manually verified, this is a time-consuming process and error-prone.

## **Goal:** 
Convert criteria to machine-readable YAML and build a program that checks athlete eligibility from CSV results, plus an interactive dashboard.

## **Deliverables**:
- YAML criteria (per sport)

- Python rule engine (eligibility checker)

- Streamlit dashboard for exploration

## **Outcome**: 
Automated checks for six winter sports with athlete-level pass/partial/fail indicators and qualification path tracing.

# **1. Introduction**

The selection of Swiss athletes for the Olympic Games is a highly regulated and complex process. In Switzerland, the national selection criteria are defined by Swiss Olympic in collaboration with the relevant sports federations. Each sport applies its own specific requirements, ensuring that only athletes who meet a precise set of conditions are eligible for the Olympic Games.

Currently, these selection criteria are published in PDF format, which makes the verification process time-consuming. When federations propose athletes for the Olympic Games, Swiss Olympic must manually check each candidate against the relevant criteria. This manual approach creates inefficiencies in the process.

For this reason, we were assigned the task of designing a system that translates the selection criteria for the Olympic Winter Games 2026 in Milano Cortina into a machine-readable format (YAML file) and developing a program that uses a list of results in CSV format to automatically check which Swiss athletes meet the selection criteria.

The project will therefore consist of creating a program capable of importing a results list in CSV format and automatically checking which Swiss athletes meet, partially meet, or fail to meet the selection criteria (YAML file). Building on this, a notebook-based interface and a Streamlit interface, that provide an interactive dashboard which allows users to filter by sport and discipline and display detailed information on results.

## **How to run the application**

In order to run the application, you simply have to press the "Run all" Button at the top of the collab. You will be prompted to connect to a Google Drive Account. Make sure you connect to the Google Account you are also logged into the collab with. Along with the Colab link, you have received an invitation link to a google drive folder. Accept the invitation and rightclick the folder. Select "Add to MyDrive". After that, the code blocks should run. You can then scroll down to Codeblock Number 9 and then click the URL. In the output, you will see a link like this: ".....cloudflare.com". Click it and a new window should appear in your browser. The app might take some time to load. In Codeblock Number 10 a second more detailed interface was created with streamlit . To run it follow the instructions above and below the code.

# **2. Required Packages**

In [1]:
### Codeblock 1

import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

#**3. Data Preparation**

In this project, two types of data were provided by Swiss Olympic:


1.   CSV file containing a list of results of the athletes
2.   YAML files containing the selection criteria for the Olympic Winter Games 2026 in Milano Cortina

##**3.1 CSV Data**
The CSV file contains competition results for 180 Swiss athletes. It includes 39 variables and 2,433 observations. Below, you can see the structure of the dataframe, along with a table describing the most relevant variables.

|Column |Discription |
------|-----
Date | The date on which the competition or event took place
Comp.SetDetail |The detailed description of the competition set
Sport | The sport in which the athlete/team competed
Discipline| The specific discipline within the sport
Gender  |The gender category of the event
Class   |The competition class or age group
Rank  | The finishing position of the athlete/team in that event
Person/Team | Names of the team members that competed
Person   |Name of the person that competed
DoB | Date of birth of the athlete
Country   | The country represented by the athlete or team
Result  | Performance outcome in the event which can be a time or points
Host City| The city where the competition took place

###**3.1.1 Loading CSV Data**

In [ ]:
### Codeblock 2
#load the data
df = pd.read_csv('/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Results_Test_Version.csv', sep=';', on_bad_lines='skip')

In [ ]:
### Codeblock 3
# Display the first 5 rows of the DataFrame
display(df.head())

# Display the column names and their data types
display(df.info())

# Display a summary of the DataFrame
display(df.describe())

display(df)

,Date,Year,Competition,CompetitionSet,Comp.SetDetail,Sport,Discipline,Gender,Class,Phase,...,Sec/Mtr/Pts,Host City,Host Country,Host Continent,# Participants,# Countries,# Continents,World Ranking,Rank Within Country,Is Olympic Discipline
0,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,12.5km Mass Start,Women,Seniors,NaN,...,"2500,70",Lenzerheide,Switzerland,Europe,30,14,1,NaN,1,Yes
1,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,12.5km Mass Start,Women,Seniors,NaN,...,"2564,70",Lenzerheide,Switzerland,Europe,30,14,1,NaN,2,Yes
2,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,15km Mass Start,Men,Seniors,NaN,...,"2425,30",Lenzerheide,Switzerland,Europe,30,13,2,NaN,1,Yes
3,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,15km Mass Start,Men,Seniors,NaN,...,"2472,60",Lenzerheide,Switzerland,Europe,30,13,2,NaN,2,Yes
4,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,15km Mass Start,Men,Seniors,NaN,...,"2474,60",Lenzerheide,Switzerland,Europe,30,13,2,NaN,3,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2434 entries, 0 to 2433
Data columns (total 38 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2434 non-null   object
 1   Year                   2434 non-null   int64
 2   Competition            2434 non-null   object
 3   CompetitionSet         2434 non-null   object
 4   Comp.SetDetail         2434 non-null   object
 5   Sport                  2434 non-null   object
 6   Discipline             2434 non-null   object
 7   Gender                 2434 non-null   object
 8   Class                  2434 non-null   object
 9   Phase                  0 non-null      float64
 10  Rank                   2434 non-null   object
 11  Medal                  160 non-null    object
 12  Team Members           2434 non-null   object
 13  Person/Team            2434 non-null   object
 14  Person                 2353 non-null   object
 15  Person First Name      2353 non-null   object
 16  Person Last Name       2353 non-null   object
 17  PersonGender           2353 non-null   object
 18  Team                   2434 non-null   object
 19  Nationality            2353 non-null   object
 20  DoB                    2353 non-null   object
 21  YoB                    0 non-null      float64
 22  Age (days)             2433 non-null   object
 23  Age                    2433 non-null   float64
 24  Country                2434 non-null   object
 25  Country Code           2434 non-null   object
 26  Continent              2434 non-null   object
 27  Result                 1798 non-null   object
 28  Sec/Mtr/Pts            1798 non-null   object
 29  Host City              2359 non-null   object
 30  Host Country           2359 non-null   object
 31  Host Continent         2359 non-null   object
 32  # Participants         2434 non-null   int64
 33  # Countries            2434 non-null   int64
 34  # Continents           2434 non-null   int64
 35  World Ranking          268 non-null    float64
 36  Rank Within Country    2434 non-null   int64
 37  Is Olympic Discipline  2138 non-null   object
dtypes: float64(4), int64(5), object(29)
memory usage: 722.7+ KB

None

,Year,Phase,YoB,Age,# Participants,# Countries,# Continents,World Ranking,Rank Within Country
count,2434.000000,0.0,0.0,2433.000000,2434.000000,2434.000000,2434.000000,268.000000,2434.000000
mean,2025.326623,NaN,NaN,26.744760,54.967132,17.414133,3.728431,11.477612,2.658176
std,0.632499,NaN,NaN,4.127516,25.046142,6.422850,0.971753,11.523769,2.120652
min,2024.000000,NaN,NaN,16.000000,7.000000,6.000000,1.000000,4.000000,0.000000
25%,2025.000000,NaN,NaN,24.000000,32.000000,13.000000,3.000000,7.000000,1.000000
50%,2025.000000,NaN,NaN,26.000000,56.000000,16.000000,4.000000,8.000000,2.000000
75%,2026.000000,NaN,NaN,30.000000,66.000000,21.000000,4.000000,10.000000,4.000000
max,2026.000000,NaN,NaN,39.000000,183.000000,63.000000,6.000000,133.000000,13.000000

,Date,Year,Competition,CompetitionSet,Comp.SetDetail,Sport,Discipline,Gender,Class,Phase,...,Sec/Mtr/Pts,Host City,Host Country,Host Continent,# Participants,# Countries,# Continents,World Ranking,Rank Within Country,Is Olympic Discipline
0,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,12.5km Mass Start,Women,Seniors,NaN,...,"2500,70",Lenzerheide,Switzerland,Europe,30,14,1,NaN,1,Yes
1,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,12.5km Mass Start,Women,Seniors,NaN,...,"2564,70",Lenzerheide,Switzerland,Europe,30,14,1,NaN,2,Yes
2,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,15km Mass Start,Men,Seniors,NaN,...,"2425,30",Lenzerheide,Switzerland,Europe,30,13,2,NaN,1,Yes
3,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,15km Mass Start,Men,Seniors,NaN,...,"2472,60",Lenzerheide,Switzerland,Europe,30,13,2,NaN,2,Yes
4,2025/02/23 00:00:00,2025,IBU World Championships,World Championships,IBU World Championships,Biathlon,15km Mass Start,Men,Seniors,NaN,...,"2474,60",Lenzerheide,Switzerland,Europe,30,13,2,NaN,3,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2429,2025/03/13 00:00:00,2025,FIS Freeski World Cup,(World) Cup standings,FIS Freeski World Cup standings,Freestyle Skiing,Aerials,Men,Seniors,NaN,...,"196,00",NaN,NaN,NaN,45,9,4,NaN,2,Yes
2430,2025/03/11 00:00:00,2025,FIS Freeski World Cup,(World) Cup standings,FIS Freeski World Cup standings,Freestyle Skiing,Moguls,Men,Seniors,NaN,...,"4,00",NaN,NaN,NaN,59,13,4,NaN,1,Yes
2431,2025/03/11 00:00:00,2025,FIS Freeski World Cup,(World) Cup standings,FIS Freeski World Cup standings,Freestyle Skiing,Moguls,Men,Seniors,NaN,...,"1,00",NaN,NaN,NaN,59,13,4,NaN,2,Yes
2432,2025/02/15 00:00:00,2025,FIS Freeski World Cup,(World) Cup standings,FIS Freeski World Cup standings,Freestyle Skiing,Halfpipe,Men,Seniors,NaN,...,"31,00",NaN,NaN,NaN,46,10,4,NaN,1,Yes
2433,2025/02/15 00:00:00,2025,FIS Freeski World Cup,(World) Cup standings,FIS Freeski World Cup standings,Freestyle Skiing,Halfpipe,Men,Seniors,NaN,...,"24,00",NaN,NaN,NaN,46,10,4,NaN,2,Yes

##**3.1.2 Transforming CSV Data**
The dataset of the athletes was prepared for the filter logic by dropping all columns that were not needed as well as the creation of a new column calles "Combined_Sport" which is a combination of the columns Sport and Discipline which is later used to as a filter criteria.

In [ ]:
### Codeblock 4
# Dropping Phase and YoB columns
data = df.drop(columns=["Phase", "YoB", "Medal"])

df["Combined_Sport"] = df["Sport"].astype(str) + "_" + df["Discipline"]

display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2434 entries, 0 to 2433
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2434 non-null   object
 1   Year                   2434 non-null   int64
 2   Competition            2434 non-null   object
 3   CompetitionSet         2434 non-null   object
 4   Comp.SetDetail         2434 non-null   object
 5   Sport                  2434 non-null   object
 6   Discipline             2434 non-null   object
 7   Gender                 2434 non-null   object
 8   Class                  2434 non-null   object
 9   Phase                  0 non-null      float64
 10  Rank                   2434 non-null   object
 11  Medal                  160 non-null    object
 12  Team Members           2434 non-null   object
 13  Person/Team            2434 non-null   object
 14  Person                 2353 non-null   object
 15  Person First Name      2353 non-null   object
 16  Person Last Name       2353 non-null   object
 17  PersonGender           2353 non-null   object
 18  Team                   2434 non-null   object
 19  Nationality            2353 non-null   object
 20  DoB                    2353 non-null   object
 21  YoB                    0 non-null      float64
 22  Age (days)             2433 non-null   object
 23  Age                    2433 non-null   float64
 24  Country                2434 non-null   object
 25  Country Code           2434 non-null   object
 26  Continent              2434 non-null   object
 27  Result                 1798 non-null   object
 28  Sec/Mtr/Pts            1798 non-null   object
 29  Host City              2359 non-null   object
 30  Host Country           2359 non-null   object
 31  Host Continent         2359 non-null   object
 32  # Participants         2434 non-null   int64
 33  # Countries            2434 non-null   int64
 34  # Continents           2434 non-null   int64
 35  World Ranking          268 non-null    float64
 36  Rank Within Country    2434 non-null   int64
 37  Is Olympic Discipline  2138 non-null   object
 38  Combined_Sport         2434 non-null   object
dtypes: float64(4), int64(5), object(30)
memory usage: 741.7+ KB

None

##**3.2 YAML Data**

The YAML files define the criteria for Swiss athletes to qualify for the Milano Olympic Games. In this project, six files were used, each containing the selection for the sport below:


1.   Alpine Skiing
2.   Biathlon
3.   Bobsleigh
4.   Cross-Country Skiing
5.   Figure Skating
6.   Freestyle Skiing

These YAML files are stored in a <a href="https://drive.google.com/drive/u/0/folders/1H0pUbvQlnMUeWHYqN49wI8QiwAPm4RMn">Google Drive repository </a>. The qualification rules were originally provided by Swiss Olympic in a PDF document and were then manually converted into YAML format for easier processing and automation.

###**3.2.1 Loading YAML Data**

In [ ]:
### Codeblock 5
#load YAML file

import yaml

# loading biathlon YAML file
biathlon_path = "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Biathlon_Hauptkriterien.txt"


with open(biathlon_path, "r", encoding="utf-8-sig") as biathlon_file:
    text = biathlon_file.read().replace('\t', '  ')
    biathlon_rules = yaml.safe_load(text)

print(biathlon_rules)


# loading Freestyle Skiing YAML file
Freestyle_Skiing_yaml_path = "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Freestyle_Skiing_Hauptkriterien.txt"

with open(Freestyle_Skiing_yaml_path, "r", encoding="utf-8-sig") as Freestyle_Skiing_file:
    text = Freestyle_Skiing_file.read().replace('\t', '  ')
    Freestyle_Skiing_rules = yaml.safe_load(text)

print(Freestyle_Skiing_rules)


# loading Figure Skating YAML file
Figure_Skating_yaml_path = "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Figure_Skating_Adjusted.txt"

with open(Figure_Skating_yaml_path, "r", encoding="utf-8-sig") as Figure_Skating_file:
    text = Figure_Skating_file.read().replace('\t', '  ')
    Figure_Skating_file_rules = yaml.safe_load(text)

print(Figure_Skating_file_rules)


# loading Cross_Country_Skiing YAML file
Cross_Country_Skiing_yaml_path = "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Cross_Country_Skiing_Hauptkriterien.txt"

with open(Cross_Country_Skiing_yaml_path, "r", encoding="utf-8-sig") as Cross_Country_Skiing_file:
    text = Cross_Country_Skiing_file.read().replace('\t', '  ')
    Cross_Country_Skiing_rules = yaml.safe_load(text)

print(Cross_Country_Skiing_rules)


# loading Bobsleigh YAML file
Bobsleigh_yaml_path = "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Bobsleigh_Hauptkriterien.txt"

with open(Bobsleigh_yaml_path, "r", encoding="utf-8-sig") as Bobsleigh_file:
    text = Bobsleigh_file.read().replace('\t', '  ')
    Bobsleigh_rules = yaml.safe_load(text)

print(Bobsleigh_rules)


# loading Alpine Skiing YAML file
Alpine_Skiing_yaml_path = "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Alpine_Skiing_Hauptkriterien.txt"

with open(Alpine_Skiing_yaml_path, "r", encoding="utf-8-sig") as Alpine_Skiing_file:
    text = Alpine_Skiing_file.read().replace('\t', '  ')
    Alpine_Skiing_rules = yaml.safe_load(text)

print(Alpine_Skiing_rules)

{'Sport': 'Biathlon', 'Is Olympic Discipline': 'Yes', 'Class': 'Seniors', 'Team Members': 'No', 'selection_paths': {'any_of': [{'all_of': [{'condition': {'description': 'Top-3 at World Championships 2025', 'Comp.SetDetail': 'IBU World Championships', 'Year': 2025, 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-30 in World Cup 2025/2026', 'Comp.SetDetail': 'BMW IBU World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 30]}, 'count_at_least': 1}}]}, {'all_of': [{'condition': {'description': 'Top-6 in World Cup 2024/2025', 'Comp.SetDetail': 'BMW IBU World Cup', 'Date': {'interval': ['2024-11-30', '2025-03-23']}, 'Rank': {'interval': [1, 6]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-25 in World Cup 2025/2026', 'Comp.SetDetail': 'BMW IBU World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 1}}]}, {'condition': {'description': 'Top-15 in World Cup 2025/2026', 'Comp.SetDetail': 'BMW IBU World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 15]}, 'count_at_least': 1}}, {'condition': {'description': '2x Top-25 in World Cup 2025/2026', 'Comp.SetDetail': 'BMW IBU World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 2}}, {'all_of': [{'condition': {'description': 'Top-5 in IBU Cup 2025/2026', 'Comp.SetDetail': 'IBU Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 5]}, 'count_at_least': 1}}, {'condition': {'description': '2x Top-30 in World Cup 2025/2026', 'Comp.SetDetail': 'BMW IBU World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 30]}, 'count_at_least': 2}}]}]}}
{'Sport': 'Freestyle Skiing', 'Is Olympic Discipline': 'Yes', 'Team Members': 'No', 'Class': 'Seniors', 'qualification_groups': {'Group_A': {'priority': 1, 'description': 'Priority group - qualifies first', 'selection_paths': {'any_of': [{'all_of': [{'condition': {'description': 'Top-3 at World Championships 2025', 'Comp.SetDetail': 'FIS Freestyle World Ski Championships', 'Year': 2025, 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-8 in World Cup 2025/26', 'Comp.SetDetail': 'FIS Freeski World Cup', 'Date': {'interval': ['2025-07-01', '2026-01-25']}, 'Rank': {'interval': [1, 8]}, 'count_at_least': 1}}]}, {'all_of': [{'condition': {'description': 'Top-3 in World Cup Standings 2024/2025', 'Comp.SetDetail': 'FIS Freeski World Cup Standings', 'Year': 2025, 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-8 in World Cup 2025/26', 'Comp.SetDetail': 'FIS Freeski World Cup', 'Date': {'interval': ['2025-07-01', '2026-01-25']}, 'Rank': {'interval': [1, 8]}, 'count_at_least': 1}}]}, {'condition': {'description': '2x Top-3 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Freeski World Cup', 'Date': {'interval': ['2025-07-01', '2026-01-25']}, 'Rank': {'interval': [1, 3]}, 'count_at_least': 2}}]}}, 'Group_B': {'priority': 2, 'description': 'Secondary group - qualifies if places remain', 'selection_paths': {'any_of': [{'condition': {'description': 'Top-8 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Freeski World Cup', 'Date': {'interval': ['2025-07-01', '2026-01-25']}, 'Rank': {'interval': [1, 8]}, 'count_at_least': 1}}, {'discipline_specific_routes': {'Aerials': {'Women': {'rank_threshold': 12, 'description': '2x Top-12 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 16, 'description': '2x Top-16 (one must be World Cup 2025/2026)'}}, 'Moguls': {'Women': {'rank_threshold': 16, 'description': '2x Top-16 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 20, 'description': '2x Top-20 (one must be World Cup 2025/2026)'}}, 'Dual Moguls': {'Women': {'rank_threshold': 16, 'description': '2x Top-16 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 20, 'description': '2x Top-20 (one must be World Cup 2025/2026)'}}, 'Ski Cross': {'Women': {'rank_threshold': 12, 'description': '2x Top-12 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 20, 'description': '2x Top-20 (one must be World Cup 2025/2026)'}}, 'Big Air': {'Women': {'rank_threshold': 12, 'description': '2x Top-12 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 20, 'description': '2x Top-20 (one must be World Cup 2025/2026)'}}, 'Slopestyle': {'Women': {'rank_threshold': 12, 'description': '2x Top-12 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 20, 'description': '2x Top-20 (one must be World Cup 2025/2026)'}}, 'Halfpipe': {'Women': {'rank_threshold': 12, 'description': '2x Top-12 (one must be World Cup 2025/2026)'}, 'Men': {'rank_threshold': 16, 'description': '2x Top-16 (one must be World Cup 2025/2026)'}}}}]}}}, 'eligible_competitions_for_route_b2': ['World Cup 2025/2026 (REQUIRED - at least 1)', 'World Championships 2025', 'World Cup 2024/2025', 'Additional World Cup 2025/2026']}
{'Sport': 'Figure Skating', 'Class': 'Seniors', 'Team Members': 'No', 'Is Olympic Discipline': 'Yes', 'selection_paths': {'any_of': [{'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU World Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2025-07-31']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU Grand Prix Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU Challenger Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU Olympic Qualifier', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'ISU OWG Test Event', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Women', 'Result': {'ge': 185}, 'Comp.SetDetail': 'National Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU World Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2025-07-31']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU Grand Prix Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU Challenger Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU Olympic Qualifier', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'ISU OWG Test Event', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Singles', 'Gender': 'Men', 'Result': {'ge': 210}, 'Comp.SetDetail': 'National Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU World Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2025-07-31']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU Grand Prix Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU Challenger Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU Olympic Qualifier', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'ISU OWG Test Event', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Ice Dance', 'Gender': 'Mixed', 'Result': {'ge': 165}, 'Comp.SetDetail': 'National Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU World Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-01-01', '2025-07-31']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU European Figure Skating Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU Grand Prix Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU Challenger Senior', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU Olympic Qualifier', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'ISU OWG Test Event', 'Date': {'interval': ['2025-01-01', '2026-01-18']}, 'count_at_least': 1}}, {'condition': {'Discipline': 'Pairs', 'Gender': 'Mixed', 'Result': {'ge': 170}, 'Comp.SetDetail': 'National Championships', 'Date': {'interval': ['2025-08-01', '2026-01-18']}, 'count_at_least': 1}}]}}
{'Sport': 'Cross-Country Skiing', 'Is Olympic Discipline': 'Yes', 'Team Members': 'No', 'Class': 'Seniors', 'selection_paths': {'any_of': [{'all_of': [{'condition': {'description': 'Top-3 at World Championships 2025', 'Comp.SetDetail': 'FIS Nordic World Ski Championships', 'Year': 2025, 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-30 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 30]}, 'count_at_least': 1}}]}, {'all_of': [{'condition': {'description': 'Top-3 at U23 World Championships 2025', 'Comp.SetDetail': 'FIS Nordic Under 23 World Ski Championships', 'Year': 2025, 'Class': 'Under 23', 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-25 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 1}}]}, {'all_of': [{'condition': {'description': 'Top-3 in World Cup 2024/2025', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2024-11-29', '2025-07-31']}, 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-25 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 1}}]}, {'condition': {'description': 'Top-15 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 15]}, 'count_at_least': 1}}, {'condition': {'description': '2x Top-25 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 2}}, {'all_of': [{'condition': {'description': 'Top-3 in Continental Cup 2025/2026', 'Comp.SetDetail': 'FESA Cross-Country Continental Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 3]}, 'count_at_least': 1}}, {'any_of': [{'condition': {'description': 'Top-25 in World Cup 2024/2025', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2024-11-29', '2025-07-31']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-25 in World Cup 2025/2026', 'Comp.SetDetail': 'FIS Cross-Country World Cup', 'Date': {'interval': ['2025-08-01', '2026-01-21']}, 'Rank': {'interval': [1, 25]}, 'count_at_least': 1}}]}]}]}}
{'Sport': 'Bobsleigh', 'Is Olympic Discipline': 'Yes', 'Class': 'Seniors', 'Team Members': 'No', 'selection_paths': {'any_of': [{'all_of': [{'condition': {'description': 'Top-6 in World Cup 2025/2026', 'Comp.SetDetail': 'IBSF World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 6]}, 'count_at_least': 1}}, {'any_of': [{'condition': {'description': 'Top-6 at World Championships 2025', 'Comp.SetDetail': 'IBSF World Championships', 'Year': 2025, 'Rank': {'interval': [1, 6]}, 'count_at_least': 1}}, {'condition': {'description': 'Top-6 in World Cup Lillehammer 2024/2025', 'Comp.SetDetail': 'IBSF World Cup', 'Date': {'interval': ['2025-02-03', '2025-02-09']}, 'Host City': 'Lillehammer', 'Rank': {'interval': [1, 6]}, 'count_at_least': 1}}]}]}, {'condition': {'description': '2x Top-12 in World Cup 2025/2026 (requires commitment until 2030)', 'Comp.SetDetail': 'IBSF World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 12]}, 'count_at_least': 2, 'special_note': 'COMMITMENT_2030_REQUIRED'}}, {'all_of': [{'condition': {'description': '2x Top-14 in World Cup 2025/2026', 'Comp.SetDetail': 'IBSF World Cup', 'Date': {'interval': ['2025-11-01', '2026-01-18']}, 'Rank': {'interval': [1, 14]}, 'count_at_least': 2}}, {'condition': {'description': 'Age 27 or younger', 'Age': {'max': 27}}}]}]}}
{'Sport': 'Alpine Skiing', 'Class': 'Seniors', 'Team Members': 'No', 'Is Olympic Discipline': 'Yes', 'selection_paths': {'any_of': [{'condition': {'description': 'Top-7 in World Cup 2025/2026', 'Comp.SetDetail': 'Audi FIS Ski World Cup', 'Date': {'interval': ['2025-10-01', '2026-01-25']}, 'Rank': {'interval': [1, 7]}, 'count_at_least': 1}}, {'condition': {'description': '2x Top-15 in World Cup 2025/2026', 'Comp.SetDetail': 'Audi FIS Ski World Cup', 'Date': {'interval': ['2025-10-01', '2026-01-25']}, 'Rank': {'interval': [1, 15]}, 'count_at_least': 2}}]}}

##**4. Sport–Discipline Inventory & Combined_Sport Keys**

The code below inventories the dataset and confirms the discipline-level filter keys. It first groups results by Sport to produce a dictionary of each sport’s unique Disciplines, helping spot duplicates or naming inconsistencies. It then prints all unique Combined_Sport values (Sport_Discipline), which are the exact keys used for discipline-level filtering in the eligibility checker and dashboard.

In [ ]:
### Codeblock 6
# Display list of Combined_Sport Column
sport_dict = (
    df.groupby("Sport")["Discipline"]
      .apply(lambda x: list(set(x)))
      .to_dict()
)

print(sport_dict)

print(df["Combined_Sport"].unique())

{'Alpine Skiing': ['Slalom', 'Downhill', 'Super G', 'Giant Slalom'], 'Biathlon': ['10km Sprint', '15km Individual', '10km Pursuit', '12.5km Pursuit', '15km Mass Start', '20km Individual', '7.5km Sprint', '12.5km Individual', '12.5km Mass Start'], 'Bobsleigh': ['2-Man', 'Monobob', '4-Man'], 'Cross-Country Skiing': ['50km Classic Style', '20km Freestyle', 'Sprint Freestyle', '20km Classic Style', 'Sprint Classic Style', '50km Freestyle', '10km Freestyle', '10km Classic Style', 'Overall Standings', '20km Skiathlon'], 'Figure Skating': ['Pairs', 'Ice Dance', 'Singles'], 'Freestyle Skiing': ['Ski Cross', 'Big Air', 'Halfpipe', 'Slopestyle', 'Dual Moguls', 'Aerials', 'Moguls', 'Aerials Team']}
['Biathlon_12.5km Mass Start' 'Biathlon_15km Mass Start'
 'Biathlon_20km Individual' 'Biathlon_15km Individual'
 'Biathlon_10km Pursuit' 'Biathlon_12.5km Pursuit' 'Biathlon_10km Sprint'
 'Biathlon_7.5km Sprint' 'Biathlon_12.5km Individual'
 'Figure Skating_Singles' 'Figure Skating_Pairs'
 'Figure Skating_Ice Dance' 'Cross-Country Skiing_50km Freestyle'
 'Cross-Country Skiing_10km Classic Style'
 'Cross-Country Skiing_20km Skiathlon'
 'Cross-Country Skiing_Sprint Freestyle'
 'Cross-Country Skiing_50km Classic Style'
 'Cross-Country Skiing_10km Freestyle'
 'Cross-Country Skiing_20km Classic Style'
 'Cross-Country Skiing_20km Freestyle'
 'Cross-Country Skiing_Sprint Classic Style'
 'Cross-Country Skiing_Overall Standings' 'Bobsleigh_2-Man'
 'Bobsleigh_4-Man' 'Bobsleigh_Monobob' 'Alpine Skiing_Slalom'
 'Alpine Skiing_Giant Slalom' 'Alpine Skiing_Super G'
 'Alpine Skiing_Downhill' 'Freestyle Skiing_Aerials'
 'Freestyle Skiing_Halfpipe' 'Freestyle Skiing_Big Air'
 'Freestyle Skiing_Aerials Team' 'Freestyle Skiing_Dual Moguls'
 'Freestyle Skiing_Ski Cross' 'Freestyle Skiing_Slopestyle'
 'Freestyle Skiing_Moguls']

# **5. Logic for Eligibility**

While implementing the eligibility logic, we encountered differences in the YAML rule schemas across sports. For example, Biathlon uses an additional nesting level called "all_off" that Alpine Skiing does not. To handle this, we needed to add criteria to our eligibility logic.


## **Sport vs. Discipline Filtering**

The code works reliably when filtering by Sport. Following stakeholder feedback (Lionel), discipline-level filtering was also required. To address this, we introduced a Combined_Sport column (Sport + "_" + Discipline), which enables queries at the discipline level and produces lists of eligible athletes for a specific discipline.

At present, discipline-level results are not always consistent. In some cases, there is insufficient data to determine eligibility, while in others certain filters in the code exclude results. These cases have been documented as current limitations.

# **Function Overview**
Below is a concise description of each function.

## **`normalize_filtered_df(df)`**

Cleans and standardizes the data to make later comparisons reliable. It copies the table, converts “Date” to a timezone-free datetime column (Date_dt), coerces “Year” into nullable integers (Year_int), parses “Rank” as numeric (Rank_num), trims whitespace in key text fields (competition, sport, discipline), ensures a “Person” column exists, and constructs a numeric result column (Result_num) from common score fields when available.

## **`get_selection_paths(rules, group="Group_A")`**
Normalizes differently shaped YAML rule files to a single structure: {"any_of": [...]}. If rules contain selection_paths, that block is returned. If rules are grouped under qualification_groups, the requested group (or the group with the lowest priority value) is selected and its selection_paths returned. If rules expose a top-level any_of, it is wrapped accordingly. This removes schema differences for downstream logic.

## **`mask_for_condition(df, cond)`**

Builds a boolean mask marking rows that satisfy one condition. It supports exact competition name matches, specific years, inclusive date intervals, inclusive rank intervals, case-insensitive equality for “Discipline” and “Gender”, and numeric result thresholds via ge, le, or an interval. The mask is later used to isolate rows that meet the specified criteria.

## **`eligible_for_condition(df, mask, count_at_least, entity_col="Person")`**
Determines which entities (athletes) meet a minimum frequency within the masked rows. It counts appearances of entity_col among matches and returns the set whose counts are at least count_at_least.

## **`eval_all_of(df, path, entity_col="Person")`**

Evaluates routes that require multiple conditions simultaneously. A single condition is treated as a one-step list; an all_of list is processed condition by condition. For each step, the eligible set is computed, and the intersection across steps is taken so that only entities satisfying every condition remain.

## **`eval_any_of(df, rules, entity_col="Person")`**
Implements the top-level OR logic. Each entry under any_of—either a single condition or an all_of block—is evaluated, and the union of all resulting eligible sets is returned. An entity qualifies if it meets at least one route.

## **`eligibility_checker(rules, df, sport_key, filter_col="Sport", group="Group_A")`**

Coordinates the workflow. It first filters rows by the chosen sport key in the specified column, then normalizes the filtered data. Next, it selects the appropriate rule block via get_selection_paths (group-aware) and evaluates those rules with eval_any_of. The final output is a sorted list of eligible athlete names.

# **Workflow Summary**
A call provides rules, results table, and an optional sport/discipline filter. The checker narrows the dataset to the targeted sport, standardizes columns for consistent comparisons, normalizes rule schemas to a uniform any_of/all_of structure, and applies the combined AND/OR logic (date, rank, discipline, gender, score thresholds). The output is the list of athletes who satisfy at least one qualifying route, returned as an ordered list.

In [ ]:
### Codeblock 7


def normalize_filtered_df(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    # Dates to datetime
    if "Date" in out.columns:
        out["Date_dt"] = pd.to_datetime(out["Date"], errors="coerce", utc=True).dt.tz_localize(None)
    else:
        out["Date_dt"] = pd.NaT

    # Year to int (coerce invalid to NaN then drop in comparisons)
    if "Year" in out.columns:
        out["Year_int"] = pd.to_numeric(out["Year"], errors="coerce").astype("Int64")
    else:
        out["Year_int"] = pd.Series([pd.NA] * len(out), dtype="Int64")

    # Rank to numeric (strip non-digits like "DNS", "DNF", etc.)
    if "Rank" in out.columns:
        out["Rank_num"] = pd.to_numeric(out["Rank"], errors="coerce")
    else:
        out["Rank_num"] = np.nan

    # Normalize strings we match exactly
    for col in ["Comp.SetDetail", "CompetitionSet", "Sport", "Discipline", "Combined_Sport"]:
        if col in out.columns:
            out[col] = out[col].astype(str).str.strip()

    # Person column (entity key)
    if "Person" not in out.columns:
        out["Person"] = ""

    # create a numeric result column (try common score fields)
    out["Result_num"] = pd.to_numeric(out.get("Result", np.nan), errors="coerce")
    if out["Result_num"].isna().all():
        for alt in ["Score", "Points", "Total", "TotalScore", "Total_Score"]:
            if alt in out.columns:
                out["Result_num"] = out["Result_num"].fillna(pd.to_numeric(out[alt], errors="coerce"))

    return out

# make sure all Sports work, even if the yaml files have different formats
def get_selection_paths(rules: dict, group: str | None = "Group_A") -> dict:
    """
    Always return {"any_of": [...]} no matter how the YAML is structured.
    Supports:
      - {"selection_paths": {"any_of": [...]}}
      - {"qualification_groups": {"Group_A": {"priority": 1, "selection_paths": {...}}, ...}}
      - {"any_of": [...]}
    """
    # 1) Direct selection_paths
    if "selection_paths" in rules:
        sp = rules["selection_paths"]
        return sp if isinstance(sp, dict) and "any_of" in sp else {"any_of": sp}

    # 2) Grouped rules
    if "qualification_groups" in rules:
        groups = rules["qualification_groups"] or {}
        # explicit group if provided
        if group and group in groups:
            sp = groups[group].get("selection_paths", {})
            return sp if "any_of" in sp else {"any_of": sp}
        # else pick lowest priority
        if groups:
            best_name = min(groups, key=lambda name: groups[name].get("priority", float("inf")))
            sp = groups[best_name].get("selection_paths", {})
            return sp if "any_of" in sp else {"any_of": sp}

    # 3) Raw any_of at top-level
    if "any_of" in rules:
        return {"any_of": rules["any_of"]}

    return {"any_of": []}



def mask_for_condition(df: pd.DataFrame, cond: dict) -> pd.Series:
    """
    cond looks like:
      {
        "Comp.SetDetail": "BMW IBU World Cup",
        "Year": 2025,
        "Date": {"interval": ["2025-11-01", "2026-01-18"]},
        "Rank": {"interval": [1, 30]},
        "count_at_least": 1
      }
    """
    #initialize all as True
    mask = pd.Series(True, index=df.index)

    # Check if Competition "BMW IBU World Cup" matches
    if "Comp.SetDetail" in cond:
        mask &= (df.get("Comp.SetDetail", "") == str(cond["Comp.SetDetail"]).strip())

    #Check if the year of the competition matches
    if "Year" in cond:
        # Compare to normalized Int64 year
        target_year = cond["Year"]
        mask &= (df["Year_int"] == target_year)

    # Interval checks (inclusive)
    if "Date" in cond and isinstance(cond["Date"], dict) and "interval" in cond["Date"]:
        start_str, end_str = cond["Date"]["interval"]
        start = pd.to_datetime(start_str, utc=True).tz_localize(None)
        end = pd.to_datetime(end_str, utc=True).tz_localize(None)
        mask &= (df["Date_dt"] >= start) & (df["Date_dt"] <= end)

    if "Rank" in cond and isinstance(cond["Rank"], dict) and "interval" in cond["Rank"]:
        lo, hi = cond["Rank"]["interval"]
        mask &= (df["Rank_num"] >= lo) & (df["Rank_num"] <= hi)

    # case-insensitive equality for Discipline / Gender, added this part to make Figure Skating work
    if "Discipline" in cond:
        left = df.get("Discipline", "").astype(str).str.strip().str.casefold()
        right = str(cond["Discipline"]).strip().casefold()
        mask &= (left == right)

    if "Gender" in cond:
        left = df.get("Gender", "").astype(str).str.strip().str.casefold()
        right = str(cond["Gender"]).strip().casefold()
        mask &= (left == right)

    # NEW: numeric Result thresholds
    if "Result" in cond and isinstance(cond["Result"], dict):
        r = cond["Result"]
        val = pd.to_numeric(df.get("Result_num", np.nan), errors="coerce")
        if "interval" in r:
            lo, hi = map(float, r["interval"])
            mask &= (val >= lo) & (val <= hi)
        if "ge" in r:
            mask &= (val >= float(r["ge"]))
        if "le" in r:
            mask &= (val <= float(r["le"]))

    return mask



def eligible_for_condition(df: pd.DataFrame, mask: pd.Series, count_at_least: int, entity_col: str = "Person") -> set:
    """
    Given a mask, return set of entities that appear at least count_at_least times.
    """
    hits = df.loc[mask, entity_col].dropna()
    if hits.empty:
        return set()
    counts = hits.value_counts()
    return set(counts[counts >= count_at_least].index)



def eval_all_of(df: pd.DataFrame, path: dict, entity_col: str = "Person") -> set:
    """
    path can be:
      - {"all_of": [{"condition": {...}}, {"condition": {...}}]}
      - {"condition": {...}}   # treat as single-step all_of
    """
    # Normalize: if a bare "condition" is provided, treat it as all_of with one step
    if "condition" in path and "all_of" not in path:
        path = {"all_of": [ {"condition": path["condition"]} ]}

    groups = []
    for step in path.get("all_of", []):
        cond = step.get("condition", {})
        mask = mask_for_condition(df, cond)
        threshold = int(cond.get("count_at_least", 1))
        ok = eligible_for_condition(df, mask, threshold, entity_col=entity_col)
        groups.append(ok)

    if not groups:
        return set()

    eligible = groups[0]
    for s in groups[1:]:
        eligible &= s
    print(f"eval_all_of: found {len(eligible)} eligible entities across {len(groups)} groups.")
    return eligible


def eval_any_of(df: pd.DataFrame, rules: dict, entity_col: str = "Person") -> set:
    """
    rules: {"any_of": [ {"condition": {...}}, {"all_of": [...]}, ... ]}
    Returns union of entities that satisfy at least one path.
    """
    winners = set()
    for path in rules.get("any_of", []):
        # Delegate to eval_all_of which now handles both shapes
        winners |= eval_all_of(df, path, entity_col=entity_col)
    return winners



def eligibility_checker(
    rules: dict,
    df: pd.DataFrame,
    sport_key: str,
    filter_col: str = "Combined_Sport",          # set to "Combined_Sport" if that's what you're passing
    group: str | None = "Group_A",
) -> list[str]:

    # 1) filter rows for this sport
    filtered = df[df[filter_col].astype(str).str.strip() == str(sport_key).strip()].copy()
    if filtered.empty:
        return []

    # 2) normalize columns
    filtered = normalize_filtered_df(filtered)

    # 3) pick the correct selection_paths (handles top-level any_of, selection_paths, or qualification_groups)
    selection_paths = get_selection_paths(rules, group=group)

    # 4) evaluate rules
    eligible_set = eval_any_of(filtered, selection_paths, entity_col="Person")

    # 5) stable list
    return sorted(eligible_set)

#chose wether you want to filter for Sport or Discipline, then chose specific Sport/Discipline
filter_col = "Combined_Sport"
sport_key = "Alpine Skiing_Downhill"
rules = Alpine_Skiing_rules
group = "Group_A"
eligible_athletes = eligibility_checker(rules, df, sport_key, filter_col, group)
print(eligible_athletes)

['Alexis Monney', 'Corinne Suter', 'Franjo von Allmen', 'Justin Murisier', 'Lara Gut-Behrami', 'Lars Rösti', 'Malorie Blanc', 'Marco Kohler', 'Marco Odermatt', 'Stefan Rogentin']

#**6. Eligibility Routes**

##**6.1 Enhanced Qualification Path Function**


The get_athletes_by_qualification_path in codeblock 8 is robust because it accepts the full rules dict and uses get_selection_paths(...) to normalize all common YAML shapes—including plain any_of, nested selection_paths, and grouped qualification_groups like Group_A. It also lets the caller choose the filter column (e.g., "Sport" or "Combined_Sport") instead of hard-coding one, produces readable path labels by joining condition descriptions with “ + ”, and reuses the same shared helpers (normalize_filtered_df, get_selection_paths, eval_all_of) as the main eligibility flow for consistent behavior. In practice, this means broader schema compatibility, clearer output, and more informative errors across sports whose YAMLs aren’t identical.

In [ ]:
### Codeblock 8
#Adjusted get_athletes_by_qualification_path
def get_athletes_by_qualification_path(
    rules: dict,
    df: pd.DataFrame,
    sport_key: str,
    filter_col: str = "Combined_Sport",      # set to "Combined_Sport" if needed
    group: str | None = "Group_A",  # used when rules have qualification_groups
    entity_col: str = "Person",
) -> dict[str, list[str]]:
    """
    Return {path_name: [sorted athletes qualifying via that path]}.
    """

    # 1) filter rows for this sport/discipline
    filtered = df[df[filter_col].astype(str).str.strip() == str(sport_key).strip()].copy()
    if filtered.empty:
        return {"error": f"No data found for '{sport_key}' in column '{filter_col}'."}

    # 2) normalize columns (dates, year, rank, scores, strings)
    filtered = normalize_filtered_df(filtered)

    # 3) normalize rules to {"any_of": [...]} using existing helper
    selection_paths = get_selection_paths(rules, group=group)
    any_of_paths = selection_paths.get("any_of", [])

    # 4) evaluate each path separately (reuse eval_all_of)
    path_results: dict[str, list[str]] = {}

    def _name(path: dict, idx: int) -> str:
        # prefer human-readable description if present
        if "condition" in path:
            d = path["condition"].get("description")
            if isinstance(d, str) and d.strip():
                return d.strip()
        if "all_of" in path:
            parts = [step.get("condition", {}).get("description", "").strip()
                     for step in path.get("all_of", [])]
            parts = [p for p in parts if p]
            if parts:
                return " + ".join(parts)
        return f"Path_{idx}"

    for i, path in enumerate(any_of_paths, start=1):
        path_name = _name(path, i)
        try:
            elig_set = eval_all_of(filtered, path, entity_col=entity_col)
            path_results[path_name] = sorted(elig_set)
        except Exception as e:
            path_results[path_name] = []
            print(f"Error processing {path_name}: {e}")

    return path_results

  #test with biathlon

print("Test Qualification by Path function")

sport_key = "Cross-Country Skiing_Sprint Freestyle"

results = get_athletes_by_qualification_path(
    rules=Cross_Country_Skiing_rules,  # <-- full dict, not ["selection_paths"]
    df=df,
    sport_key=sport_key,
    filter_col="Combined_Sport",
    group="Group_A",
)

if "error" in results:
    print(f" {results['error']}")
else:
    print("SIMPLE PATH RESULTS:")
    print("-" * 30)
    for path_name, athletes in results.items():
        print(f"{path_name}: {athletes}")

    print(f"\n SUMMARY:")
    total_athletes = sum(len(athletes) for athletes in results.values())
    print(f"Total athletes found across all paths: {total_athletes}")

    # Show which paths have athletes
    active_paths = [path for path, athletes in results.items() if athletes]
    print(f"Paths with qualifying athletes: {active_paths}")

Test Qualification by Path function
SIMPLE PATH RESULTS:
------------------------------
Top-3 at World Championships 2025 + Top-30 in World Cup 2025/2026: ['Nadine Fähndrich']
Top-3 at U23 World Championships 2025 + Top-25 in World Cup 2025/2026: []
Top-3 in World Cup 2024/2025 + Top-25 in World Cup 2025/2026: ['Nadine Fähndrich']
Top-15 in World Cup 2025/2026: ['Valerio Grond']
2x Top-25 in World Cup 2025/2026: ['Valerio Grond']
Top-3 in Continental Cup 2025/2026: []

 SUMMARY:
Total athletes found across all paths: 4
Paths with qualifying athletes: ['Top-3 at World Championships 2025 + Top-30 in World Cup 2025/2026', 'Top-3 in World Cup 2024/2025 + Top-25 in World Cup 2025/2026', 'Top-15 in World Cup 2025/2026', '2x Top-25 in World Cup 2025/2026']

#**7. Streamlit App**

The codeblock 9 packages the rule-engine into a Streamlit app and exposes it via a Cloudflare tunnel (handy in Colab). It installs dependencies, writes app.py with the UI to select Sport/Discipline, loads the CSV and YAML rules, and computes athletes per qualification path using the earlier helper functions. The app shows metrics, expandable path results, a summary table, and a CSV download. Finally, it launches Streamlit and prints a public URL for quick access.

In [ ]:
### Codeblock 9
# 0) Install Streamlit and download cloudflared binary
!pip -q install streamlit
!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

# 1) This is the app code. For it to work on the collab we had to repaste a lot of the basic logic from above. The effective app code starts at line 150
import pathlib, textwrap
pathlib.Path("app.py").write_text(textwrap.dedent("""
import streamlit as st
import pandas as pd
import yaml
import os
import numpy as np

# Page configuration
st.set_page_config(
    page_title="Swiss Olympic Qualification Paths",
    page_icon="🏔️",
    layout="wide"
)

# Title
st.title("🏔️ Swiss Olympic Team Selection")

# Required functions for qualification path analysis
def normalize_filtered_df(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    # Dates to datetime
    if "Date" in out.columns:
        out["Date_dt"] = pd.to_datetime(out["Date"], errors="coerce", utc=True).dt.tz_localize(None)
    else:
        out["Date_dt"] = pd.NaT

    # Year to int (coerce invalid to NaN then drop in comparisons)
    if "Year" in out.columns:
        out["Year_int"] = pd.to_numeric(out["Year"], errors="coerce").astype("Int64")
    else:
        out["Year_int"] = pd.Series([pd.NA] * len(out), dtype="Int64")

    # Rank to numeric (strip non-digits like "DNS", "DNF", etc.)
    if "Rank" in out.columns:
        out["Rank_num"] = pd.to_numeric(out["Rank"], errors="coerce")
    else:
        out["Rank_num"] = np.nan

    # Normalize strings we match exactly
    for col in ["Comp.SetDetail", "CompetitionSet", "Sport", "Discipline", "Combined_Sport"]:
        if col in out.columns:
            out[col] = out[col].astype(str).str.strip()

    # Person column (entity key)
    if "Person" not in out.columns:
        out["Person"] = ""

    # create a numeric result column (try common score fields)
    out["Result_num"] = pd.to_numeric(out.get("Result", np.nan), errors="coerce")
    if out["Result_num"].isna().all():
        for alt in ["Score", "Points", "Total", "TotalScore", "Total_Score"]:
            if alt in out.columns:
                out["Result_num"] = out["Result_num"].fillna(pd.to_numeric(out[alt], errors="coerce"))

    return out

# make sure all Sports work, even if the yaml files have different formats
def get_selection_paths(rules: dict, group: str | None = "Group_A") -> dict:
    '''
    Always return {"any_of": [...]} no matter how the YAML is structured.
    Supports:
      - {"selection_paths": {"any_of": [...]}}
      - {"qualification_groups": {"Group_A": {"priority": 1, "selection_paths": {...}}, ...}}
      - {"any_of": [...]}
    '''
    # 1) Direct selection_paths
    if "selection_paths" in rules:
        sp = rules["selection_paths"]
        return sp if isinstance(sp, dict) and "any_of" in sp else {"any_of": sp}

    # 2) Grouped rules
    if "qualification_groups" in rules:
        groups = rules["qualification_groups"] or {}
        # explicit group if provided
        if group and group in groups:
            sp = groups[group].get("selection_paths", {})
            return sp if "any_of" in sp else {"any_of": sp}
        # else pick lowest priority
        if groups:
            best_name = min(groups, key=lambda name: groups[name].get("priority", float("inf")))
            sp = groups[best_name].get("selection_paths", {})
            return sp if "any_of" in sp else {"any_of": sp}

    # 3) Raw any_of at top-level
    if "any_of" in rules:
        return {"any_of": rules["any_of"]}

    return {"any_of": []}



def mask_for_condition(df: pd.DataFrame, cond: dict) -> pd.Series:
    '''
    cond looks like:
      {
        "Comp.SetDetail": "BMW IBU World Cup",
        "Year": 2025,
        "Date": {"interval": ["2025-11-01", "2026-01-18"]},
        "Rank": {"interval": [1, 30]},
        "count_at_least": 1
      }
    '''
    #initialize all as True
    mask = pd.Series(True, index=df.index)

    # Check if Competition "BMW IBU World Cup" matches
    if "Comp.SetDetail" in cond:
        mask &= (df.get("Comp.SetDetail", "") == str(cond["Comp.SetDetail"]).strip())

    #Check if the year of the competition matches
    if "Year" in cond:
        # Compare to normalized Int64 year
        target_year = cond["Year"]
        mask &= (df["Year_int"] == target_year)

    # Interval checks (inclusive)
    if "Date" in cond and isinstance(cond["Date"], dict) and "interval" in cond["Date"]:
        start_str, end_str = cond["Date"]["interval"]
        start = pd.to_datetime(start_str, utc=True).tz_localize(None)
        end = pd.to_datetime(end_str, utc=True).tz_localize(None)
        mask &= (df["Date_dt"] >= start) & (df["Date_dt"] <= end)

    if "Rank" in cond and isinstance(cond["Rank"], dict) and "interval" in cond["Rank"]:
        lo, hi = cond["Rank"]["interval"]
        mask &= (df["Rank_num"] >= lo) & (df["Rank_num"] <= hi)

    # case-insensitive equality for Discipline / Gender, added this part to make Figure Skating work
    if "Discipline" in cond:
        left = df.get("Discipline", "").astype(str).str.strip().str.casefold()
        right = str(cond["Discipline"]).strip().casefold()
        mask &= (left == right)

    if "Gender" in cond:
        left = df.get("Gender", "").astype(str).str.strip().str.casefold()
        right = str(cond["Gender"]).strip().casefold()
        mask &= (left == right)

    # NEW: numeric Result thresholds
    if "Result" in cond and isinstance(cond["Result"], dict):
        r = cond["Result"]
        val = pd.to_numeric(df.get("Result_num", np.nan), errors="coerce")
        if "interval" in r:
            lo, hi = map(float, r["interval"])
            mask &= (val >= lo) & (val <= hi)
        if "ge" in r:
            mask &= (val >= float(r["ge"]))
        if "le" in r:
            mask &= (val <= float(r["le"]))

    return mask



def eligible_for_condition(df: pd.DataFrame, mask: pd.Series, count_at_least: int, entity_col: str = "Person") -> set:
    '''
    Given a mask, return set of entities that appear at least count_at_least times.
    '''
    hits = df.loc[mask, entity_col].dropna()
    if hits.empty:
        return set()
    counts = hits.value_counts()
    return set(counts[counts >= count_at_least].index)



def eval_all_of(df: pd.DataFrame, path: dict, entity_col: str = "Person") -> set:
    '''
    path can be:
      - {"all_of": [{"condition": {...}}, {"condition": {...}}]}
      - {"condition": {...}}   # treat as single-step all_of
    '''
    # Normalize: if a bare "condition" is provided, treat it as all_of with one step
    if "condition" in path and "all_of" not in path:
        path = {"all_of": [ {"condition": path["condition"]} ]}

    groups = []
    for step in path.get("all_of", []):
        cond = step.get("condition", {})
        mask = mask_for_condition(df, cond)
        threshold = int(cond.get("count_at_least", 1))
        ok = eligible_for_condition(df, mask, threshold, entity_col=entity_col)
        groups.append(ok)

    if not groups:
        return set()

    eligible = groups[0]
    for s in groups[1:]:
        eligible &= s
    return eligible


def get_athletes_by_qualification_path(
    rules: dict,
    df: pd.DataFrame,
    sport_key: str,
    filter_col: str = "Combined_Sport",
    group: str | None = "Group_A",
    entity_col: str = "Person",
) -> dict[str, list[str]]:
    '''
    Return {path_name: [sorted athletes qualifying via that path]}.
    '''

    # 1) Filter rows for this sport/discipline
    filtered = df[df[filter_col].astype(str).str.strip() == str(sport_key).strip()].copy()
    if filtered.empty:
        return {"error": f"No data found for '{sport_key}' in column '{filter_col}'."}

    # 2) Normalize columns
    filtered = normalize_filtered_df(filtered)

    # 3) Normalize rules to {"any_of": [...]} using existing helper
    selection_paths = get_selection_paths(rules, group=group)
    any_of_paths = selection_paths.get("any_of", [])

    # 4) Evaluate each path separately
    path_results: dict[str, list[str]] = {}

    def _name(path: dict, idx: int) -> str:
        # If single condition has description
        if "condition" in path:
            d = path["condition"].get("description")
            if isinstance(d, str) and d.strip():
                return d.strip()
        # If multiple conditions
        if "all_of" in path:
            parts = [step.get("condition", {}).get("description", "").strip()
                     for step in path.get("all_of", [])]
            parts = [p for p in parts if p]
            if parts:
                return " + ".join(parts)
        return f"Path_{idx}"

    for i, path in enumerate(any_of_paths, start=1):
        path_name = _name(path, i)
        try:
            elig_set = eval_all_of(filtered, path, entity_col=entity_col)
            path_results[path_name] = sorted(elig_set)
        except Exception as e:
            path_results[path_name] = []
            st.error(f"Error processing {path_name}: {e}")

    return path_results

# Load data function
@st.cache_data
def load_data():
    '''Load Olympic data and rules'''
    try:
        # Load CSV data
        df = pd.read_csv('/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Results_Test_Version.csv', sep=';', on_bad_lines='skip')
        df["Combined_Sport"] = df["Sport"].astype(str) + "_" + df["Discipline"]

        # Load YAML rules
        rules = {}
        yaml_files = {
            "Biathlon": "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Biathlon_Hauptkriterien.txt",
            "Alpine Skiing": "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Alpine_Skiing_Hauptkriterien.txt",
            "Freestyle Skiing": "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Freestyle_Skiing_Hauptkriterien.txt",
            "Figure Skating": "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Figure_Skating_Adjusted.txt",
            "Cross-Country Skiing": "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Cross_Country_Skiing_Hauptkriterien.txt",
            "Bobsleigh": "/content/drive/MyDrive/Swiss_winter_olympics/oly_data/Bobsleigh_Hauptkriterien.txt"
        }

        for sport_name, file_path in yaml_files.items():
            if os.path.exists(file_path):
                with open(file_path, "r", encoding="utf-8-sig") as file:
                    text = file.read().replace('\t', '  ')
                    rules[sport_name] = yaml.safe_load(text)

        return df, rules
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return None, None

# Load data
df, rules = load_data()

if df is not None and rules:
    # Sidebar for sport/discipline selection
    st.sidebar.header("🎯 Select Sport & Discipline")

    # Get unique sports and disciplines
    sports = sorted(df['Sport'].unique())
    selected_sport = st.sidebar.selectbox("Select Sport:", sports)

    # Get disciplines for selected sport
    disciplines = sorted(df[df['Sport'] == selected_sport]['Discipline'].unique())
    selected_discipline = st.sidebar.selectbox("Select Discipline:", disciplines)

    # Create combined sport key
    combined_sport = f"{selected_sport}_{selected_discipline}"

    # Main content
    st.header(f"🏆 {selected_sport} - {selected_discipline}")

    # Check if we have rules for this sport
    if selected_sport in rules:
        # Get qualification path results
        results = get_athletes_by_qualification_path(rules[selected_sport], df, combined_sport)

        if "error" not in results:
            # Display results
            st.subheader("📊 Qualification Path Results")

            # Summary statistics
            total_athletes = sum(len(athletes) for athletes in results.values())
            active_paths = [path for path, athletes in results.items() if athletes]

            # Metrics
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Total Eligible Athletes", total_athletes)
            with col2:
                st.metric("Active Qualification Paths", len(active_paths))
            with col3:
                st.metric("Total Paths Available", len(results))

            # Display athletes by path
            st.subheader("🏃‍♂️ Athletes by Qualification Path")

            for path_name, athletes in results.items():
                if athletes:  # Only show paths with athletes
                    with st.expander(f"✅ {path_name} ({len(athletes)} athletes)", expanded=True):
                        for athlete in athletes:
                            st.write(athlete)
                else:
                    with st.expander(f"❌ {path_name} (0 athletes)"):
                        st.write("No athletes qualified through this path")

            # Show all results in a table
            st.subheader("📋 Summary Table")

            # Create summary data
            summary_data = []
            for path_name, athletes in results.items():
                for athlete in athletes:
                    summary_data.append({
                        "Athlete": athlete,
                        "Qualification Path": path_name,
                        "Status": "✅ Qualified"
                    })

            if summary_data:
                summary_df = pd.DataFrame(summary_data)
                st.dataframe(summary_df, use_container_width=True)

                # Download button
                csv = summary_df.to_csv(index=False)
                st.download_button(
                    label="📥 Download Results as CSV",
                    data=csv,
                    file_name=f"{selected_sport}_{selected_discipline}_qualification_paths.csv",
                    mime="text/csv"
                )
            else:
                st.info("No athletes qualified through any path for this sport/discipline combination.")

        else:
            st.error(f"Error: {results['error']}")
    else:
        st.warning(f"No qualification rules available for {selected_sport}")

    # Debug information (collapsible)
    with st.expander("🔍 Debug Information"):
        st.write("**Data Overview:**")
        st.write(f"- Total records: {len(df):,}")
        st.write(f"- Unique athletes: {df['Person'].nunique():,}")
        st.write(f"- Sports: {len(df['Sport'].unique())}")
        st.write(f"- Disciplines: {len(df['Discipline'].unique())}")

        if selected_sport:
            sport_data = df[df['Sport'] == selected_sport]
            st.write(f"**{selected_sport} Statistics:**")
            st.write(f"- Records: {len(sport_data):,}")
            st.write(f"- Athletes: {sport_data['Person'].nunique()}")
            st.write(f"- Disciplines: {len(sport_data['Discipline'].unique())}")

            # Show available disciplines
            st.write(f"**Available Disciplines:**")
            for discipline in sport_data['Discipline'].unique():
                st.write({discipline})

        st.write(f"**Combined Sport Key:** {combined_sport}")
        st.write(f"**Available Rules:** {list(rules.keys())}")

else:
    st.error("❌ Unable to load data. Please check that the data files are available.")
    st.info("Required files:")
    st.write("- `oly_data/Results_Test_Version.csv`")
    st.write("- YAML rule files in `oly_data/` directory")
"""))

# 2) Start Streamlit in the background (bind to 0.0.0.0 so the tunnel can reach it)
import subprocess, time, re, sys
st_proc = subprocess.Popen(
    ["streamlit","run","app.py","--server.port","8501","--server.address","0.0.0.0"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
)
time.sleep(2)  # small boot delay

# 3) Start cloudflared and capture the public URL (https://xxxxx.trycloudflare.com)
cf_proc = subprocess.Popen(
    ["./cloudflared","tunnel","--url","http://localhost:8501","--no-autoupdate"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1
)

public_url = None
for line in cf_proc.stdout:
    if "trycloudflare.com" in line:
        m = re.search(r"https://[-\w\.]+trycloudflare\.com", line)
        if m:
            public_url = m.group(0)
            print("🔗 Open this URL:", public_url)
            break

# (Optional) show last few Streamlit log lines
for _ in range(10):
    l = st_proc.stdout.readline()
    if not l: break
    sys.stdout.write(l)

🔗 Open this URL: https://bottles-history-vegas-ripe.trycloudflare.com

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2025-09-19 16:29:48.108 Failed to schedule watch observer for path /content
Traceback (most recent call last):

In [ ]:
### Always run this cell before closing the collab. Delete the # in line 2 and 3 before running it.
#!pkill -f "streamlit run" || true
#!pkill -f "cloudflared tunnel" || true

^C
^C

## **8. User Interface (UI)**

### **Introduction**

The User Interface component of our Swiss Olympic Team Selection system provides an intuitive and interactive way for users to analyze athlete eligibility for the 2026 Milano Cortina Winter Olympics. This interface bridges the gap between complex qualification rules and practical decision-making, making the selection process accessible to coaches, team managers, and Olympic committee members.

### **Design Philosophy**

Our UI is built on the principle of **simplicity meets functionality**. We recognize that Olympic team selection involves complex criteria and large datasets, but the interface should remain user-friendly and efficient. The system provides both interactive widget-based interfaces for visual users and programmatic function-based interfaces for power users and automation.

### **Key Features**

#### **Interactive Data Exploration**
- **Dynamic Sport/Discipline Selection**: Dropdown menus that automatically populate based on available data
- **Real-time Eligibility Checking**: Instant results when criteria are applied
- **Athlete Performance Visualization**: Detailed competition history and ranking information

#### **Comprehensive Results Display**
- **Eligible Athletes List**: Clear presentation of qualified athletes with performance metrics
- **Competition History**: Detailed breakdown of each athlete's results and achievements
- **Data Quality Indicators**: Visual feedback on data completeness and reliability

#### **Multiple Interface Options**
- **Widget-Based Interface**: Interactive Jupyter widgets for point-and-click operation
- **Function-Based Interface**: Programmatic access for batch processing and automation
- **Hybrid Approach**: Seamless switching between interface types based on user needs

### **Technical Implementation**

The UI leverages modern Python libraries including:
- **ipywidgets**: For interactive Jupyter notebook components
- **pandas**: For data manipulation and display
- **IPython.display**: For rich output formatting
- **Custom Classes**: OlympicDataManager and EligibilityChecker for modular functionality

### **User Experience Design**

#### **Progressive Disclosure**
Information is presented in layers, starting with high-level summaries and allowing users to drill down into specific details as needed.

#### **Error Handling & Validation**
- Clear error messages for missing data or invalid selections
- Automatic data validation and quality checks
- Graceful handling of edge cases and incomplete information

#### **Responsive Feedback**
- Loading indicators during data processing
- Success/failure notifications for user actions
- Real-time updates as criteria are modified

### **Supported Sports & Disciplines**

The interface supports all major winter Olympic sports with their specific disciplines:
- **Biathlon** (12.5km Mass Start, 15km Mass Start, etc.)
- **Alpine Skiing** (Downhill, Slalom, Giant Slalom, etc.)
- **Freestyle Skiing** (Aerials, Moguls, Halfpipe, etc.)
- **Figure Skating** (Individual, Pairs, Ice Dance, etc.)
- **Cross Country Skiing** (Various distance events)
- **Bobsleigh** (2-man, 4-man, Women's events)

### **Getting Started**

The interface is designed to be self-explanatory with built-in help and examples. Users can:
1. **Load Data**: Import Olympic results and qualification rules
2. **Select Criteria**: Choose sport and discipline combinations
3. **Analyze Results**: Review eligible athletes and their performance data
4. **Export Information**: Save results for further analysis or reporting


This UI component transforms the complex process of Olympic team selection into an accessible, efficient, and reliable tool that supports data-driven decision making for the Swiss Olympic Team.

In [ ]:
### Codeblock 10
##!!!!Note: to run this part of the code you need to install Streamlit and required dependencies
!pip install streamlit
!pip install pyngrok
!pip install pandas numpy PyYAML
# 🏔️ Swiss Olympic Team Selection - Simple Interface
import pandas as pd
import numpy as np
import yaml
import os
from typing import Dict, List, Set, Any, Tuple

# Initialize global variables
notebook_df = None
notebook_data_loaded = False

# Data loading function
def load_olympic_data_notebook():
    """Load Olympic data from CSV file"""
    global notebook_df, notebook_data_loaded
    csv_path = "oly_data/Results_Test_Version.csv"

    try:
        if not os.path.exists(csv_path):
            print(f"❌ File not found: {csv_path}")
            return False

        notebook_df = pd.read_csv(csv_path, sep=";", on_bad_lines="skip")
        notebook_df["Combined_Sport"] = notebook_df["Sport"].astype(str) + "_" + notebook_df["Discipline"]
        notebook_data_loaded = True

        print("✅ Data loaded successfully!")
        print(f"📊 Total records: {len(notebook_df)}")
        print(f"🏃‍♂️ Unique athletes: {notebook_df['Person'].nunique()}")
        print(f"🏅 Sports: {len(notebook_df['Sport'].unique())}")

        return True

    except Exception as e:
        print(f"❌ Error loading data: {e}")
        return False

# Eligibility checking functions (from your notebook)
def normalize_filtered_df(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize data types for filtering operations"""
    out = df.copy()

    # Dates to datetime
    if "Date" in out.columns:
        out["Date_dt"] = pd.to_datetime(out["Date"], errors="coerce", utc=True).dt.tz_localize(None)
    else:
        out["Date_dt"] = pd.NaT

    # Year to int
    if "Year" in out.columns:
        out["Year_int"] = pd.to_numeric(out["Year"], errors="coerce").astype("Int64")
    else:
        out["Year_int"] = pd.Series([pd.NA] * len(out), dtype="Int64")

    # Rank to numeric
    if "Rank" in out.columns:
        out["Rank_num"] = pd.to_numeric(out["Rank"], errors="coerce")
    else:
        out["Rank_num"] = np.nan

    # Normalize strings
    for col in ["Comp.SetDetail", "CompetitionSet", "Sport", "Discipline", "Combined_Sport"]:
        if col in out.columns:
            out[col] = out[col].astype(str).str.strip()

    # Person column
    if "Person" not in out.columns:
        out["Person"] = ""

    return out

def mask_for_condition(df: pd.DataFrame, cond: dict) -> pd.Series:
    """Create boolean mask for a single condition"""
    mask = pd.Series(True, index=df.index)

    if "Comp.SetDetail" in cond:
        mask &= (df.get("Comp.SetDetail", "") == str(cond["Comp.SetDetail"]).strip())

    if "Year" in cond:
        target_year = cond["Year"]
        mask &= (df["Year_int"] == target_year)

    if "Date" in cond and isinstance(cond["Date"], dict) and "interval" in cond["Date"]:
        start_str, end_str = cond["Date"]["interval"]
        start = pd.to_datetime(start_str, utc=True).tz_localize(None)
        end = pd.to_datetime(end_str, utc=True).tz_localize(None)
        mask &= (df["Date_dt"] >= start) & (df["Date_dt"] <= end)

    if "Rank" in cond and isinstance(cond["Rank"], dict) and "interval" in cond["Rank"]:
        lo, hi = cond["Rank"]["interval"]
        mask &= (df["Rank_num"] >= lo) & (df["Rank_num"] <= hi)

    return mask

def eligible_for_condition(df: pd.DataFrame, mask: pd.Series, count_at_least: int, entity_col: str = "Person") -> set:
    """Return entities that meet the count threshold"""
    hits = df.loc[mask, entity_col].dropna()
    if hits.empty:
        return set()
    counts = hits.value_counts()
    return set(counts[counts >= count_at_least].index)

def eval_all_of(df: pd.DataFrame, path: dict, entity_col: str = "Person") -> set:
    """Evaluate "all_of" conditions (intersection)"""
    groups = []
    for step in path.get("all_of", []):
        cond = step.get("condition", {})
        mask = mask_for_condition(df, cond)
        threshold = int(cond.get("count_at_least", 1))
        ok = eligible_for_condition(df, mask, threshold, entity_col=entity_col)
        groups.append(ok)

    if not groups:
        return set()

    eligible = groups[0]
    for s in groups[1:]:
        eligible &= s
    return eligible

def eval_any_of(df: pd.DataFrame, rules: dict, entity_col: str = "Person") -> set:
    """Evaluate "any_of" conditions (union)"""
    winners = set()
    for path in rules.get("any_of", []):
        winners |= eval_all_of(df, path, entity_col=entity_col)
    return winners

def check_eligibility_notebook(df: pd.DataFrame, rules: dict, sport_discipline: str) -> Tuple[List, Dict]:
    """Main eligibility checking function"""
    try:
        # Filter data for the specific sport/discipline
        filtered = df[df["Combined_Sport"].astype(str).str.strip() == str(sport_discipline).strip()].copy()

        if filtered.empty:
            return [], {"error": f"No data found for {sport_discipline}"}

        # Normalize data
        filtered = normalize_filtered_df(filtered)

        # Evaluate rules
        selection_paths = rules.get("selection_paths", {})
        eligible_set = eval_any_of(filtered, selection_paths, entity_col="Person")

        # Prepare detailed results
        results = {
            "total_records": len(filtered),
            "eligible_count": len(eligible_set),
            "sport_discipline": sport_discipline,
            "athletes_data": filtered[filtered["Person"].isin(eligible_set)] if eligible_set else pd.DataFrame()
        }

        return sorted(eligible_set), results

    except Exception as e:
        return [], {"error": str(e)}

def load_yaml_rules_notebook(sport_name: str) -> Dict:
    """Load YAML rules for a specific sport"""
    yaml_files = {
        "Biathlon": "Biathlon_Hauptkriterien.txt",
        "Alpine Skiing": "Alpine_Skiing_Hauptkriterien.txt",
        "Freestyle Skiing": "Freestyle_Skiing_Hauptkriterien.txt",
        "Figure Skating": "Figure_Skating_Hauptkriterien.txt",
        "Cross Country Skiing": "Cross_Country_Skiing_Hauptkriterien.txt",
        "Bobsleigh": "Bobsleigh_Hauptkriterien.txt"
    }

    if sport_name not in yaml_files:
        return {}

    yaml_path = os.path.join("oly_data/", yaml_files[sport_name])

    try:
        if not os.path.exists(yaml_path):
            return {}

        with open(yaml_path, "r", encoding="utf-8-sig") as file:
            text = file.read().replace("\t", "  ")
            rules = yaml.safe_load(text)
            return rules

    except Exception as e:
        print(f"Error loading YAML for {sport_name}: {e}")
        return {}

# Simple Interface Functions (No Widgets)
def show_athlete_details(athlete_name):
    """Show detailed athlete information"""
    if not notebook_data_loaded:
        print("❌ Please load data first using load_olympic_data_notebook()")
        return

    athlete_data = notebook_df[notebook_df["Person"] == athlete_name]

    print(f"🏃‍♂️ ATHLETE DETAILS: {athlete_name}")
    print("=" * 50)
    print(f"📊 Total Competitions: {len(athlete_data)}")
    print(f"🏅 Sports: {len(athlete_data['Sport'].unique())}")
    print(f"🌍 Countries: {len(athlete_data['Country'].unique())}")

    # Best rank
    ranks = pd.to_numeric(athlete_data["Rank"], errors="coerce").dropna()
    if not ranks.empty:
        print(f"🥇 Best Rank: {ranks.min()}")
        print(f"📉 Worst Rank: {ranks.max()}")

    print("\n🏅 SPORTS:")
    for sport in athlete_data["Sport"].unique():
        print(f"  • {sport}")

    print("\n🎯 DISCIPLINES:")
    for discipline in athlete_data["Discipline"].unique():
        print(f"  • {discipline}")

    print("\n📅 RECENT COMPETITIONS:")
    recent_data = athlete_data[["Date", "Competition", "Sport", "Discipline", "Rank", "Country"]].head(10)
    display(recent_data)

def check_eligibility_simple(sport, discipline):
    """Check athlete eligibility for a sport/discipline combination"""
    if not notebook_data_loaded:
        print("❌ Please load data first using load_olympic_data_notebook()")
        return

    print(f"🔄 Checking eligibility for {sport} - {discipline}...")

    # Load YAML rules
    rules = load_yaml_rules_notebook(sport)

    if rules:
        # Run eligibility check
        combined_sport = f"{sport}_{discipline}"
        eligible_athletes, results = check_eligibility_notebook(notebook_df, rules, combined_sport)

        # Display results
        if "error" not in results:
            print(f"🏆 ELIGIBILITY RESULTS FOR {sport.upper()} - {discipline.upper()}")
            print("=" * 60)
            print(f"📊 Records Analyzed: {results['total_records']}")
            print(f"✅ Eligible Athletes: {results['eligible_count']}")
            print()

            if eligible_athletes:
                print("🥇 ELIGIBLE ATHLETES:")
                print("-" * 30)
                for i, athlete in enumerate(eligible_athletes, 1):
                    print(f"{i}. {athlete}")

                # Show detailed data
                if not results["athletes_data"].empty:
                    print("\n📊 COMPETITION DETAILS:")
                    print("-" * 30)
                    display_cols = ["Person", "Date", "Competition", "Rank", "Result"]
                    available_cols = [col for col in display_cols if col in results["athletes_data"].columns]
                    display(results["athletes_data"][available_cols])
            else:
                print("❌ No eligible athletes found for the current criteria.")
        else:
            print(f"❌ {results['error']}")
    else:
        print(f"❌ Could not load qualification rules for {sport}")

def list_athletes():
    """List all available athletes"""
    if not notebook_data_loaded:
        print("❌ Please load data first using load_olympic_data_notebook()")
        return

    athletes = sorted(notebook_df["Person"].dropna().unique())
    print(f"🏃‍♂️ Available Athletes ({len(athletes)} total):")
    print("=" * 40)
    for i, athlete in enumerate(athletes, 1):
        print(f"{i:3d}. {athlete}")

def list_sports():
    """List all available sports and their disciplines"""
    if not notebook_data_loaded:
        print("❌ Please load data first using load_olympic_data_notebook()")
        return

    sports = sorted(notebook_df["Sport"].unique())
    print(f"🏅 Available Sports ({len(sports)} total):")
    print("=" * 40)

    for sport in sports:
        disciplines = sorted(notebook_df[notebook_df["Sport"] == sport]["Discipline"].unique())
        print(f"\n🏔️ {sport}:")
        for discipline in disciplines:
            print(f"   • {discipline}")

# Main interface function
def show_interface():
    """Show the main interface instructions"""
    print("🏔️ Swiss Olympic Team Selection Interface")
    print("=" * 50)
    print()
    print("📋 Available Functions:")
    print("1. load_olympic_data_notebook() - Load the Olympic data")
    print("2. list_athletes() - Show all available athletes")
    print("3. show_athlete_details('Athlete Name') - Show athlete details")
    print("4. list_sports() - Show all sports and disciplines")
    print("5. check_eligibility_simple('Sport', 'Discipline') - Check eligibility")
    print()
    print("🎯 Example Usage:")
    print("   load_olympic_data_notebook()")
    print("   list_athletes()")
    print("   show_athlete_details('Lena Häcki-Groß')")
    print("   check_eligibility_simple('Biathlon', '12.5km Mass Start')")
    print()
    print("✅ Interface ready!")

# Show the interface
show_interface()

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.49.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.4.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.27.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (7.3.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
🏔️ Swiss Olympic Team Selection Interface
==================================================

📋 Available Functions:
1. load_olympic_data_notebook() - Load the Olympic data
2. list_athletes() - Show all available athletes
3. show_athlete_details('Athlete Name') - Show athlete details
4. list_sports() - Show all sports and disciplines
5. check_eligibility_simple('Sport', 'Discipline') - Check eligibility

🎯 Example Usage:
   load_olympic_data_notebook()
   list_athletes()
   show_athlete_details('Lena Häcki-Groß')
   check_eligibility_simple('Biathlon', '12.5km Mass Start')

✅ Interface ready!

User Workflow
Streamlit Interface Workflow:
Launch application and load Olympic data
Navigate to Athlete Explorer for individual analysis
Use Eligibility Checker for team selection analysis
Review Data Overview for statistical insights
Notebook Interface Workflow:
Execute data loading function
Run athlete listing and exploration functions
Perform eligibility checks for specific sport-discipline combinations
Analyze results through programmatic data manipulation
Installation and Setup in terminal:
```
# python3 -m venv olympic_env
source olympic_env/bin/activate
pip install pandas pyyaml numpy streamlit
```
Streamlit Application Launch:


```
# Launch Streamlit with Colab integration
!streamlit run olympic_app.py --server.port 8501 --server.headless true
```

#**9. Conclusion**

This project demonstrates that Swiss Olympic’s selection criteria, originally published in PDFs, can be converted into a structured machine-readable format (YAML) and systematically applied to real competition data (CSV) to assess athlete eligibility.

The algorithm developed is capable of handling consistent schema designs, including grouped conditions and mixed AND/OR logic. It standardizes event data (dates, ranks, results) and evaluates athletes against the rules to classify them as eligible, partially eligible, or not eligible.

To extend functionality, discipline-level filtering was implemented by combining sport and discipline into a single key, along with transparent qualification paths that clearly indicate how an athlete qualified.

The implementation of the interactive interfaces supports quick lookups by sport, discipline, and athlete. This solution reduces manual review effort and ensures consistency and traceability in selection decisions for the Milano–Cortina 2026 Olympics. While current limitations include incomplete discipline-level data and varying schema complexity, the approach remains scalable and ready for future extension.

#**10. Challenges and Reflection**

One of the main challenges in this assignment was the coordination and assignment of the workload between the four group members. We were quite fast creating a quick mvp with Generative AI consisting of a dashboard in streamlit where the user could pick a sport and see the results of all athletes qualifying for the sport. However the different disciplines within the sport were not considered. From there we splitted the work into the following parts.

1. Loading the data and transform yaml files into a dictionary
1. Datapreparation
2. Creation of YAML files for all sports
3. Filtering Logic
4. Streamlit Dashboard
5. General documentation / Introduction

Handling differences in the availability and structure of eligibility data was another Challenge we faced. While four out of six sports used a consistent YAML format, making their integration relatively straightforward, the remaining two required significantly more effort due to entirely new structure levels. To address this, we extended the base eligibility logic to incorporate the grouping requirements of Freestyle Skiing. For Figure Skating, which relies on score-based criteria, we chose a more pragmatic approach by adapting its YAML file to align with the existing templates. This solution allowed us to unify the logic across all sports and generate accurate results. Ultimately, the project highlights the importance of flexible data handling and pragmatic design choices when integrating diverse eligibility rules.

Since our project was built in a modular way, we had to make sure the different parts (data processing, rule engine, and UI) worked well together. To keep things simple, we defined clear connections between the components early on, which let us work on them in parallel without constantly checking in with each other. We also ran regular integration tests, which helped us spot small issues early before they could turn into bigger problems later.

A final challenge was ensuring a lean and accessible way to present the results to stakeholders. Our goal was to minimize the need for them to interact directly with code while still allowing transparency and reproducibility. In the end, we settled on using Google Colab, which hosts all the code and integrates both a Streamlit app and an output-based interface. With this setup, stakeholders can simply be invited to the Colab, inspect the underlying implementation if they wish, and run the Streamlit app—hosted via Cloudflare’s free tier—without any additional setup.

# **Limitations**

However, the project also comes with some limitations. Several disciplines currently do not yield results because of insufficient data points, which restricts the eligibility logic. Since the application filters at the discipline level, athletes must meet all conditions within a single discipline, which further limits the applicability.

Another limitation is that adding new athlete data or extending the application to additional sports or disciplines requires some coding knowledge. Ideally, such functionality should be integrated directly into the interface so that non-technical users can upload data or expand coverage without modifying the code. Due to limited time, these features were not implemented in the current version.

Lastly, in a production-ready version, the app should present richer athlete profiles—showing each athlete’s discipline(s), the specific races entered, event dates and competitions, and detailed outcomes (rank, score, etc.). This would reveal not only who qualified but also the exact performances behind every qualification.